version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/" # root package.json
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/packages/package-a" # package.json in this folder
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/packages/package-b" # another package.json
    schedule:
      interval: "weekly"
